name = "w4trc-fieldday"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[rules]]
type = "Text"
globs = ["**/*.html"]

[[d1_databases]]
binding = "DB"
database_name = "fieldday"
database_id = "cc5d37b8-f4ad-40f6-8954-485b0a3116c3"

# Deploy: wrangler secret put INGEST_SECRET
